index:
    path: /
    controller: App\Controller\DefaultController::index
push:
    path: /push
    controller: App\Controller\PushController::handle
post:
    path: /post
    controller: App\Controller\PostController::handle
